import './globals.css'
import { Inter } from 'next/font/google'
import { getSession } from './api/auth/[...nextauth]/utils'
import SessionProvider from './session-provider'
import '@fortawesome/fontawesome-svg-core/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getSession()
  return (
    <html lang="en">
      <SessionProvider session={session}>
          <body className={inter.className}>{children}</body>
      </SessionProvider>
    </html>
  )
}
